### ISSUE TITLE
Tracking changes manually

### ISSUE THREAD

**Issue by israelmuca** [henk-badenhorst/vue-hotjar#7]
First of all, thanks for the library @henk-badenhorst !

Now, for the issue, I'm running into a limitation with this library, as with the current implementation, we don't have access to the `hj` function to [track changes manually](https://help.hotjar.com/hc/en-us/articles/360034378534#track-changes-manually).

I already did a workaround using a local implementation of your library, I don't know if you're interested in a PR to add it here.

If yes, I'd be glad to open a PR with the proposed change.

Thanks!

**Comment by henk-badenhorst** [comment]
Hi @israelmuca. Apologies for the delayed response, Yes, you are welcome to submit a PR. I will also look into this in more detail in the meantime. Thanks in advance.

**Comment by israelmuca** [comment]
Awesome! And don't worry.
I'll be doing the PR shortly.
Thanks!

**Comment by henk-badenhorst** [comment]
Hi @israelmuca have you got around to this pull request? I have had a look at it as well and am I correct in saying that you want to assign the `window.hj` property that gets initialised to a new Vue Prototype object such as `$hj`. 

Something like this: `Vue.prototype.$hj = window.hj` 

I have managed to get this working in a local experimental branch but I am having some difficulty getting it work with the ``isProduction`` property. Once the ``window.hj`` is created it means that HotJar is tracking and because the ``isProduction`` completely ignores and skips over the creation of ``window.hj`` thus ``window.hj`` is not defined when ``isProduction`` is set to ``false``.  

What is your current work around for this and do you know if there is some function on the ``window.hj`` that pauses tracking? Documentation from HotJar is very vague on this.

**Comment by henk-badenhorst** [comment]
Hi @israelmuca.  I have managed bring in this functionality in this PR #10. Could you please check it out and let me know if you are happy with the changes. I have been in contact with the HotJar team and they are providing me Business Plan access to test and document this functionality further.

**Comment by israelmuca** [comment]
Hey!
Thank you so very much! This is great!!

I did a local implementation to work through some requirements I had, but what you have is now better!
The reason I never did a PR was because I couldn't get the tests to pass.

I'll be using the library again!
Thank you!!
